config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "companies#new"
  resources :users do
    resources :companies
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :companies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :authenticate_user!

  def new
    @company = Company.new
  end

  def create
    @company = current_user.companies.build(company_params)
    if @company.save
      redirect_to user_company_path(current_user, @company)
    else
      render :new
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def update
    @company = Company.find(params[:id])
    @company.update(company_params)
    if @company.save
      redirect_to user_company_path(current_user, @company)
    else
      redirect_to :edit
    end

  end

  def index
    @companies = current_user.companies
  end

  def show
    @company = Company.find(params[:id])
  end

  private

  def company_params
    params.require(:company).permit(:name, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/edit.html.erb
<div>
  <%= simple_form_for [current_user, @company] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.button :submit, "Update", class: "btn btn-outline-success" %>
  <% end %>
</div>

app/views/companies/index.html.erb
<div class="col-md-9" >
  <div class="row">
    <div class="col-md-2">
      <h4>Name<h4>
    </div>
  </div>
  <% @companies.each do |company| %>
    <div class="row">
      <div class="col-md-2">
        <%= link_to company.name, user_company_path(current_user, company) %>
      </div>
    </div>
  <% end %>
  <div class="row mt-1">
    <div class="col-md-2">
    <%= link_to new_user_company_path(current_user) do  %>
      <div class="btn btn-outline-success">Add</div>
    <% end %>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div>
  <%= simple_form_for [current_user, @company] do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.button :submit, "Create", class: "btn btn-outline-success" %>
  <% end %>
</div>

app/views/companies/show.html.erb
<div class="col-md-9">
  <div class="row">
    <h4> Name: </h4><%= @company.name %>
    <h4> Address: </h4> <%= @company.address %>
  </div>
  <div class="row mt-2">
    <%= link_to edit_user_company_path(current_user, @company) do %>
      <div class="btn btn-outline-secondary"> Edit </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-inverse">
  <div class="container-fluid">
    <ul class="nav navbar-nav">
      <li class="nav-item">
        <%- if current_user %>
          <%= link_to "My companies", user_companies_path(current_user), class: "nav-link" %>
        <% end %>
      <li>
    </ul>
    </ul>
    <ul class="nav navbar-nav float-xs-right">
      <%- if current_user %>
      <li class="nav-item">
        <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
      </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CompanyKit</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>